services:
  postgres-docker-base-1:
    image: 'postgres:latest'
    container_name: 'postgres-docker-fsw-donalds'
    environment:
      POSTGRES_USER: admin1
      POSTGRES_PASSWORD: admin1
      POSTGRES_DB: fsw_donalds
    volumes:
      - ./initPostgres.sql:/docker-entrypoint-initdb.d/initPostgres.sql:ro
    restart: always
    ports:
      - '5440:5432'